### ISSUE TITLE
Rainlab Static Pages plugin ?

### ISSUE THREAD

**Issue by realrandal** [scottbedard/vuetober#26]
If I remember correctly, old version of Vuetober had support (or not?) of menus and Static Pages. 

As I understand CMS Pages here are totally useless because we have Vue Pages instead. But what about those generates from Static Pages plugin? Can we lay them to REST? ;)

**Comment by scottbedard** [comment]
Hmm, I'll have to look into this. I've never actually used the static pages plugin. I bet it wouldn't be too difficult though to make static pages that are rendered with no layout. If we could do this, then one could simply use axios or whatever to fetch the page content, and inject it into the page with the `v-html` directive.

**Comment by realrandal** [comment]
Static Pages plugin also generate menus that user can manage (any plugin can be integrated with it). That's why it is most used plugin from Octo marketplace.
